### ISSUE TITLE
Regarding .jar build of JDA

### ISSUE THREAD

**Issue by HaydenAtFoxHaven** [dec4234/JavaDestinyAPI#10]
Have been working with the API for sometime now and requests work fine. The problem is that JSON parsing causes a few errors.
To combat this here is a JAR file build packaged with GSON. :)
[JDestinyAPI_GSONPackaged.zip](https://github.com/dec4234/JavaDestinyAPI/files/6227258/JDestinyAPI_GSONPackaged.zip)

**Comment by dec4234** [comment]
Are you still working with the same jar that I sent a couple of months ago? I've fixed a lot of issues in more recent versions that I haven't published a jar file for.

Edit: I published a new release specifically for your purposes, [v1.2](https://github.com/dec4234/JavaDestinyAPI/releases/tag/1.2)

**Comment by HaydenAtFoxHaven** [comment]
Yes I was working with v1.1 thank you for the new release will patch if necessary
