### ISSUE TITLE
NPE Regarding Access Token?

### ISSUE THREAD

**Issue by Driftay** [dec4234/JavaDestinyAPI#13]
So the code is pretty straight forward just wanted to see if it actually worked and 
    `public static DestinyAPI api;
    public static void main(String[] args) throws LoginException {
        api = new DestinyAPI().setApiKey("api-key");
        System.out.println(api.getUser("76561198334940394"));`

Then i decided to just simply print out a BungieUser and was getting a NPE for getAccessToken.`

Caused by: java.lang.NullPointerException
	at material.DestinyAPI.getAccessToken(DestinyAPI.java:136)
	at utils.HttpUtils.<clinit>(HttpUtils.java:31)

**Comment by dec4234** [comment]
I have made a fix that should fix this problem. You can go ahead and start using the latest version.
Here is the code I used to test:
```
DestinyAPI da = new DestinyAPI().setApiKey("api-key");
System.out.println(DestinyAPI.getUser("4611686018468620320").getDisplayName());
```

**Comment by Driftay** [comment]
> I have made a fix that should fix this problem. You can go ahead and start using the latest version.
> Here is the code I used to test:
> 
> ```
> DestinyAPI da = new DestinyAPI().setApiKey("api-key");
> System.out.println(DestinyAPI.getUser("4611686018468620320").getDisplayName());
> ```

Works fine now, but I think there is a static file manager somewhere checking for a properties folder

Error: java.io.FileNotFoundException: .\config.properties (The system cannot find the file specified)

**Comment by dec4234** [comment]
Was there more to the stack trace? The most recent version of the API (not the JARs in the releases) should have no references to config.properties anymore.

**Comment by Driftay** [comment]
java.io.FileNotFoundException: .\config.properties (The system cannot find the file specified)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at utils.FileUtils.checkFileStatus(FileUtils.java:21)
	at utils.FileUtils.getInfo(FileUtils.java:42)
	at utils.HttpUtils.<clinit>(HttpUtils.java:27)
	at material.user.BungieUser.<init>(BungieUser.java:26)
	at material.DestinyAPI.getUser(DestinyAPI.java:41)
	at pw.saber.bot.DeificBot.getDriftay(DeificBot.java:47)
	at pw.saber.bot.DeificBot.main(DeificBot.java:36)

**Comment by Driftay** [comment]
One more quick question is there a method currently for getting the equipped weapons of a current class?

**Comment by dec4234** [comment]
Not at this time unfortunately, definitely something on the to do list. If you mind me asking, are you using the latest version? Because BungieUser 26 and HttpUtils line 27 don't point to anything.

**Comment by Driftay** [comment]
<dependency>
            <groupId>com.github.dec4234</groupId>
            <artifactId>JavaDestinyAPI</artifactId>
            <version>master</version>
        </dependency>

directly from the README

**Comment by dec4234** [comment]
Go ahead and try changing the version to 4d68066 (the latest commit). I'll have to look into it more a little later.
