### ISSUE TITLE
searchUsers method is very slow to return data when searching for common words

### ISSUE THREAD

**Issue by TheHanna** [dec4234/JavaDestinyAPI#16]
https://github.com/dec4234/JavaDestinyAPI/blob/bb6539869fcba9eba4f05bc9547746c8ea5fb8bd/src/main/java/net/dec4234/javadestinyapi/material/DestinyAPI.java#L235-L248

Paginating through the API automatically to get _all_ the data at once is an inefficient way handle search. This is slow when searching for common terms in a username, i.e. "guardian"

Ideally, you should simply expose the pagination and allow developers to customize this a bit so that it can be performant

**Comment by dec4234** [comment]
Do you have something like an Iterator in mind using hasNext() and next()?

**Comment by dec4234** [comment]
This has now been settled with the addition of [Pagination](https://github.com/dec4234/JavaDestinyAPI/blob/master/src/main/java/net/dec4234/javadestinyapi/utils/fast/Pagination.java) and the [updated #searchUsers(String name)](https://github.com/dec4234/JavaDestinyAPI/blob/ca114de44e354c38d052c23fe6967106cdcdb89f/src/main/java/net/dec4234/javadestinyapi/material/DestinyAPI.java#L277).
Thank you for your suggestion. Please let me know if there are any further issues.
