### ISSUE TITLE
what's ".\config.properties" ?,why i should use this?

### ISSUE THREAD

**Issue by KroFin** [dec4234/JavaDestinyAPI#21]
It was happen when i use function named "getUsersWithName()"

**Comment by dec4234** [comment]
I'll look into this. It might be a relic of the old oauth system that needs to be removed.

Update: It appears that this has been removed in recent versions. Are you using an old JAR file? Those likely contain references to config.properties that aren't present in the most recent versions on the master branch.
config.properties used to be used to hold oauth tokens before the current oauth handling system was implemented. It can be safely ignored, if you don't want it then you need to update.
