### ISSUE TITLE
External .jar build

### ISSUE THREAD

**Issue by HaydenAtFoxHaven** [dec4234/JavaDestinyAPI#6]
I would like to use the API with your wrapper. However, I don't usually use maven for my projects and was wondering if you could publish a version of the wrapper as a jar file.

**Comment by dec4234** [comment]
Thank you for showing interest in using the API. I have uploaded a .jar version inside of the release linked below. Please feel free to ask any further questions you have. Thanks!

https://github.com/dec4234/JavaDestinyAPI/releases/tag/1.1

**Comment by HaydenAtFoxHaven** [comment]
Thanks so much. Really appreciate it.
